server:
  port: 8888

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # Configuration CORS intégrée
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        # 1. Route pour l'authentification (Toujours sans filtre JWT !)
        - id: security-route
          uri: lb://SECURITY-SERVICE
          predicates:
            - Path=/auth/**

        # 2. Route pour le service Livraison (Tout ce qui commence par /LIVRAISON-SERVICE/)
        - id: livraison-route
          uri: lb://LIVRAISON-SERVICE
          predicates:
            - Path=/LIVRAISON-SERVICE/**
          filters:
            # On enlève le préfixe /LIVRAISON-SERVICE/ avant d'envoyer au microservice
            - RewritePath=/LIVRAISON-SERVICE/(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

        # 3. Route pour le service Colis
        - id: colis-route
          uri: lb://COLIS-SERVICE
          predicates:
            - Path=/COLIS-SERVICE/**
          filters:
            - RewritePath=/COLIS-SERVICE/(?<segment>.*), /$\{segment}
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/